name: Build_special_firmware

on:
  push:
    branches:
    - special_builder
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

  schedule:
    - cron: '0 * * * *'

jobs:
  tasmota_pull:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Use latest Tasmota development
      run: |
        mv README.md README.save
        git config --local user.name "Platformio BUILD"
        git switch -c work
        git remote add -f Tasmota "https://github.com/arendst/Tasmota.git"
        git merge Tasmota/development --allow-unrelated-histories
        ls *
        mv -f README.save README.md
        git add -f README.md
        git commit --allow-empty -m "use actual development" # hack to use latest dev build to compile now, not next time
    - name: Push Tasmota   # Push updates of latest Tasmota development to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'special_builder'
        force: true

  tasmota-tls:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-tls
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-gps:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-gps
        mv ./README.md ./build_output/firmware
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-battery:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-battery
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-scripting:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-scripting
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-mega:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-mega
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-thermostat:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-thermostat
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-fullrules:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-fullrules
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-platinum:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-platinum
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-minicustom:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-minicustom
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output


  tasmota32-tls:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-tls
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-zigbee:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-zigbee
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-gps:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-gps
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-battery:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-battery
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-scripting:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-scripting
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-mega:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-mega
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-ethernet:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-ethernet
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-fullrules:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-fullrules
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32-platinum:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-platinum
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output


  tasmota32-minicustom:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-minicustom
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output


  tasmota32-udisplay:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-udisplay
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota32c3:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32c3
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output


  tasmota32c3_2M:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32c3_2M
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  Upload:
    needs: [tasmota-tls, tasmota-fullrules, tasmota-platinum, tasmota-minicustom, tasmota32-scripting, tasmota32-tls, tasmota32-mega, tasmota32-fullrules, tasmota32-platinum, tasmota32-minicustom, tasmota32-ethernet, tasmota32-gps, tasmota32-udisplay, tasmota32c3, tasmota32c3_2M, tasmota32-battery]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Remove all files # We dont need any file from here
      run: |
        rm -rf *
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: firmware
        path: ./mv_firmware
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./mv_firmware
    - name: Move firmware files in sub-folders
      run: |
        mkdir -p ./firmware/tasmota/other
        mkdir -p ./firmware/tasmota32/other
        mkdir -p ./firmware/tasmota32/ESP32_needed_files/
        mkdir -p ./firmware/tasmota32/Odroid_go_and_core2_needed_files/
        mkdir -p ./firmware/tasmota32/ESP32-C3_needed_files/
        mkdir -p ./firmware/map
        mv ./mv_firmware/map/* ./firmware/map/
        mv ./mv_firmware/firmware/README.md ./
        mv ./mv_firmware/firmware/tasmota32* ./firmware/tasmota32/other/
        mv ./mv_firmware/firmware/* ./firmware/tasmota/other/
        mv ./tools/Esptool/ESP32/*.* ./firmware/tasmota32/ESP32_needed_files/
        mv ./tools/Esptool/Odroid_go_and_core2/*.* ./firmware/tasmota32/Odroid_go_and_core2_needed_files/
        mv ./tools/Esptool/ESP32-C3/*.* ./firmware/tasmota32/ESP32-C3_needed_files/
    - name: Commit files  # transfer the new binaries into the repository
      run: |
        git config --local user.name "Platformio BUILD"
        git rm -r --cached .
        git add ./README.md
        git add -f ./firmware/*.*
        git commit -m "http://tasmota.com"
    - name: Push changes  # push the firmware files to branch firmware
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'firmware'
        force: true
