name: Build_special_firmware

on:
  push:
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  tasmota_pull:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Use latest Tasmota development
      run: |
        git config --local user.name "Platformio BUILD"
        git switch -c work
        git remote add -f Tasmota "https://github.com/arendst/Tasmota.git"
        git merge Tasmota/development --allow-unrelated-histories
    - name: Push Tasmota   # Push updates of latest Tasmota development to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
        force: true

  tasmota-zigbee:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-zigbee
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-gps:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-gps
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-battery:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-battery
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-scripting:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-scripting
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-mega:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-mega
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-thermostat:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-thermostat
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-fullrules:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-fullrules
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-platinum:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-platinum
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota-minicustom:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota-minicustom
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-webcam:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-webcam
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-zigbee:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-zigbee
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-gps:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-gps
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-battery:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-battery
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-scripting:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-scripting
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-mega:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-mega
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-ethernet:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-ethernet
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-odroid:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-odroid
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32solo1:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32solo1
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-fullrules:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-fullrules
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-platinum:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-platinum
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  tasmota32-minicustom:
    needs: tasmota_pull
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: |
        platformio run -e tasmota32-minicustom
        mv ./README.md ./build_output/firmware
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output/firmware

  Upload:
    needs: [tasmota-zigbee, tasmota-fullrules, tasmota-platinum, tasmota-minicustom, tasmota32-scripting, tasmota32-mega, tasmota32-fullrules, tasmota32-platinum, tasmota32-minicustom, tasmota32-webcam, tasmota32solo1, tasmota32-ethernet, tasmota32-odroid, tasmota32-gps, tasmota32-battery]    
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Remove all files # We dont need any file from here
      run: |
        rm -rf *
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: firmware
        path: ./mv_firmware
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./mv_firmware
    - name: Move firmware files in sub-folders
      run: |
        mkdir -p ./firmware/tasmota/other
        mkdir -p ./firmware/tasmota32/other
        mkdir -p ./firmware/tasmota32/ESP32_needed_files/
        mv ./mv_firmware/README.md ./
        mv ./mv_firmware/tasmota32* ./firmware/tasmota32/other/
        mv ./mv_firmware/* ./firmware/tasmota/other/
        mv ./tools/Esptool/ESP32/*.* ./firmware/tasmota32/ESP32_needed_files/
    - name: Commit files  # transfer the new binaries into the repository
      run: |
        git config --local user.name "Platformio BUILD"
        git rm -r --cached .
        git add ./README.md
        git add -f ./firmware/*.*
        git commit -m "http://tasmota.com"
    - name: Push changes  # push the firmware files to branch firmware
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'firmware'
        force: true
